# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib tantivyr, .registration = TRUE
NULL

tnt_create_in_dir <- function(path, names, kinds, stored, indexed, fast, tokenizers, heap_mb) .Call(wrap__tnt_create_in_dir, path, names, kinds, stored, indexed, fast, tokenizers, heap_mb)

tnt_create_in_ram <- function(names, kinds, stored, indexed, fast, tokenizers, heap_mb) .Call(wrap__tnt_create_in_ram, names, kinds, stored, indexed, fast, tokenizers, heap_mb)

tnt_open_in_dir <- function(path, heap_mb) .Call(wrap__tnt_open_in_dir, path, heap_mb)

tnt_add_ <- function(idx, field_names, columns) .Call(wrap__tnt_add_, idx, field_names, columns)

tnt_delete_numeric_ <- function(idx, field, value) .Call(wrap__tnt_delete_numeric_, idx, field, value)

tnt_delete_text_ <- function(idx, field, value) .Call(wrap__tnt_delete_text_, idx, field, value)

tnt_commit_ <- function(idx) .Call(wrap__tnt_commit_, idx)

tnt_num_docs_ <- function(idx) .Call(wrap__tnt_num_docs_, idx)

tnt_count_ <- function(idx, query, default_fields, filter) .Call(wrap__tnt_count_, idx, query, default_fields, filter)

tnt_search_ <- function(idx, query, limit, default_fields, filter, highlight, snippet_chars, order_by, order_desc) .Call(wrap__tnt_search_, idx, query, limit, default_fields, filter, highlight, snippet_chars, order_by, order_desc)

tnt_schema_info_ <- function(idx) .Call(wrap__tnt_schema_info_, idx)

#' Tantivy version string.
#' @export
tantivy_version <- function() .Call(wrap__tantivy_version)

# nolint end
